### ISSUE TITLE
Updated sector data

### ISSUE THREAD

**Issue by fabio-nettis** [helldivers-2/helldivers2-api#22]
Hi there! We're working on the [HellHub API](https://github.com/hellhub-collective/api) and we have updated our sector data by leveraging the power of tideous hand-work. Feel free to snag the json file if you like!

**Comment by dealloc** [comment]
great work on the companion API, looks like we're building fairly similar things!
Wonder if there's a way we can combine our efforts, the sector data looks great but do you guys have a mapping of the identifiers somewhere?

**Comment by fabio-nettis** [comment]
@dealloc We don't have a mapping per-se but we have added all planet id's (from your json file) into each sector by taking a look at the in-game map. Then we iterate over the sectors and add it like this:

```typescript
const planetSector = sectors.find(s => {
      return s.planets.some(p => p.index === planet.index);
    });
```

We'd be happy to collaborate. We will start working on a front end soon and maybe you can get your hands dirty there.

**Comment by dealloc** [comment]
Looping over the planet list to find planets in the same sector is interesting
I'll have to see if I can reuse part of that algorithm in this API.

> We'd be happy to collaborate. We will start working on a front end soon and maybe you can get your hands dirty there.
While I am proficient in frontend development the aim for this project is to remain an API only.
Would there be changes that could interest you guys in building your frontend on top of this API?

I've been thinking a bit of a rework/redesign of the API might be necessary (as it's currently a *very* thin wrapper around the base API) and I'm definitely willing to discuss with the community what would work for them

**Comment by fabio-nettis** [comment]
@dealloc There may be the option to **merge our efforts with you and your team as repository member(s)** to provide a single source of truth for data retrieval. We have chosen TypeScript to enable collaboration for almost anyone. Next to the abstraction layer we also provide some fancy stuff like:

- Basic, Nested and Multi Filtering
- Pagination
- Sorting
- Field Selection

Check out the [postman collection](https://github.com/dealloc/helldivers2-api/files/14638181/postman.json) for more information on the endpoints we provide. Would be amazing if we could team up 🚀

**Comment by fabio-nettis** [comment]
As you already said well we provide a lot of "convenience" features and additional data. We even added some more cool stuff to the API you might enjoy, take a look at our [latest release](https://github.com/helldivers-companion/api/releases/tag/v1.2.0). Of course your community can gladly use our API (and yes you are free to grab the stratagem data too) 🚀 

For us it would be interesting to work together with the other community API maintainers to create a single API that can be used in the long-term and is maintained by the community.

> The primary reason I chose Elixir is that it would allow for fancy features in the future like a websocket connection so people can just get new data pushed to them rather than having to pull information on an interval.

PS: I don't foresee and issues with a web socket implementation for our API.

**Comment by fabio-nettis** [comment]
> As you already said well we provide a lot of "convenience" features and additional data. We even added some more cool stuff to the API you might enjoy, take a look at our [latest release](https://github.com/helldivers-companion/api/releases/tag/v1.2.0). Of course your community can gladly use our API (and yes you are free to grab the stratagem data too) 🚀
> 
> For us it would be interesting to work together with the other community API maintainers to create a single API that can be used in the long-term and is maintained by the community.
> 
> > The primary reason I chose Elixir is that it would allow for fancy features in the future like a websocket connection so people can just get new data pushed to them rather than having to pull information on an interval.
> 
> PS: I don't foresee and issues with a web socket implementation for our API.

@dealloc Let me know if this is something you would be interested in. You can also contact me on discord: fabio.nettis

**Comment by dealloc** [comment]
@fabio-nettis I'd definitely be interested in this.
As you can see we've created https://github.com/helldivers-2 as a community organisation to centralize this sort of development.

Things like the sector information you provided are being centralized under [helldivers-2/json](https://github.com/helldivers-2/json) to make sharing this sort of information even more accessible to the community.

If you're not already, I recommend dropping in at https://discord.gg/KS8kHVKX and tag me there
